on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/60 * * * *'
    
jobs:
  Build-n-Deploy-Eleventy-To-Docker-Hub:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]


    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build          

      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ github.event.repository.name }}-${{ github.ref_name }}
        
      - name: Docker Push
        run: docker push ${{ github.event.repository.name }}-${{ github.ref_name }}

